name: my_cart_express
description: A new Flutter project.

publish_to: 'none'

version: 3.0.6+9

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:

  badges: ^3.0.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  dio_http_cache: ^0.3.0
  file_picker: ^5.2.5
  firebase_core: ^2.6.1
  firebase_dynamic_links: ^5.0.15
  firebase_messaging: ^14.2.4
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-alpha.6
  flutter_local_notifications: ^13.0.0
  flutter_multi_formatter: ^2.10.2
  flutter_xlider:
    git:
      url: https://github.com/rutvikgumasana/flutter_xlider
  get: ^4.6.5
  get_storage: ^2.1.1
  http: ^0.13.5
  image_cropper: ^3.0.1
  image_picker: ^0.8.6+1
  intl: ^0.18.0
  permission_handler: ^10.2.0
  share_plus: ^6.3.1
  syncfusion_flutter_pdfviewer: ^21.1.41
  timelines: ^0.1.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/roboto/
    - assets/fonts/poppins/

  fonts:
    - family: roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
          weight: 800
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 600
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Light.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
          weight: 300
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
